- name: V-22599 Check
  shell: ls -lL /etc/security/audit_user
  args:
    executable: /bin/bash
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22599 Check 2
  shell: ls -lL /etc/security/audit_user | awk '$1 ~ /\+/ {print $9}'
  args:
    executable: /bin/bash
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22599 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: "----------------------------------------------------------------------------------------------"
    block: |
      V-22599
      The /etc/security/audit_user file must not have an extended ACL.
      If the permissions of the file contain a "+", an extended ACL is present, this is a finding.
      Procedure:
      # ls -lL /etc/security/audit_user
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      -
      This is NOT a finding
      -
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-22599 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: "----------------------------------------------------------------------------------------------"
    block: |
      V-22599
      The /etc/security/audit_user file must not have an extended ACL.
      If the permissions of the file contain a "+", an extended ACL is present, this is a finding.
      Procedure:
      # ls -lL /etc/security/audit_user
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ====================================================================
      This is a FINDING
      -
  when: checkmyconf2.stdout != ""

- name: V-22599 Fix-1
  shell:  chmod A- /etc/security/audit_user
  args:
    executable: /bin/bash
  ignore_errors: True
  when: (checkmyconf2.stdout != "" and FIX == 1)
