- name: V-790 Check
  shell: ls -lRa /usr/lib/netsvc/yp /var/yp
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-790 Check 2
  shell: find /usr/lib/netsvc/yp /var/yp -exec ls -ld {} \; | awk '$3 !~ /root|sys|bin/'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-790 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: "----------------------------------------------------------------------------------------------"
    block: |
      V-790
      NIS/NIS+/yp files must be group-owned by root, sys, or bin.
      If the file ownership is not root, sys, or bin, this is a finding.
      Procedure:
      # ls -lRa /usr/lib/netsvc/yp /var/yp
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      -
      This is NOT a finding
      -
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-790 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: "----------------------------------------------------------------------------------------------"
    block: |
      V-790
      NIS/NIS+/yp files must be group-owned by root, sys, or bin.
      If the file ownership is not root, sys, or bin, this is a finding.
      Procedure:
      # ls -lRa /usr/lib/netsvc/yp /var/yp
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ====================================================================
      This is a FINDING
      -
  when: checkmyconf2.stdout != ""

- name: V-790 Fix-1
  file: path="{{item}}" group=root
  with_items: "{{checkmyconf2.stdout_lines}}"
  when: (checkmyconf2.stdout != "" and FIX == 1)
