###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-4250 Check
  shell: if [ $(zonename) = "global" ]; then bootadm list-menu | awk "-F:" '/menu.lst/ {print $2}' | xargs ls -ld; else echo "This system `zonename` does not meet the requirement"; fi
  args:
    executable: /bin/bash
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-4250 Check 2
  shell: if [ $(zonename) = "global" ]; then bootadm list-menu | awk "-F:" '/menu.lst/ {print $2}' | xargs ls -ld; else echo "This system `zonename` does not meet the requirement N/A"; fi | awk '/-rw-------|requirement/ {print $9}'
  args:
    executable: /bin/bash
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-4250 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-4250"
      rule_id="SV-4250r3_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The system's boot loader configuration file(s) must have mode 0600 or less permissive.</title>
      <discussion>File permissions greater than 0600 on boot loader configuration files could allow an unauthorized user to view or modify sensitive information pertaining to system boot instructions.</discussion>
      <check_content>This check applies to the global zone only. Determine the type of zone that you are currently securing.

      # zonename

      If the command output is "global", this check applies.

      Check the permission of the menu.lst file.

      On systems that have a ZFS root, the menu.lst file is typically located at /pool-name/boot/grub/menu.lst where "pool-name" is the mount point for the top-level dataset.

      On systems that have a UFS root, the menu.lst file is typically located at /boot/grub/menu.lst .  

      Procedure:
      # ls -lL /pool-name/boot/grub/menu.lst 
      or
      # ls -lL /boot/grub/menu.lst 

      If menu.lst has a mode more permissive than 0600, this is a finding.</check_content>
      <fix_text>Change the mode of the menu.lst file to 0600.

      # chmod 0600 /pool-name/boot/grub/menu.lst 
      or
      # chmod 0600 /boot/grub/menu.lst </fix_text>

- name: V-4250 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: "----------------------------------------------------------------------------------------------"
    block: |
      <procedure>
        Procedure: 
        # if [ $(zonename) = "global" ]
        #   then bootadm list-menu | awk "-F:" '/menu.lst/ {print $2}' | xargs ls -ld      
        #   else echo "This system `zonename` does not meet the requirement"
        # fi
      </procedure>
      <output>
        V-4250
        The system's boot loader configuration file(s) must have mode 0600 or less permissive.
        If menu.lst has a mode more permissive than 0600, this is a finding.
        Procedure:
        # if [ $(zonename) = "global" ]
        #   then bootadm list-menu | awk "-F:" '/menu.lst/ {print $2}' | xargs ls -ld      
        #   else echo "This system `zonename` does not meet the requirement"
        # fi
        OUTPUT:
        ->  {{ checkmyconf1.stdout }}
        -
        This is NOT a finding
        -
      </output>
      <comments>menu.lst has a mode equal or less permissive than 0600</comments>
      <status>Not a Finding</status>
      <ccis>
        <cci>CCI-</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout != "" and REPORT == 1 or ansible_architecture != "i386")

- name: V-4250 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: "----------------------------------------------------------------------------------------------"
    block: |
      <procedure>
        Procedure: 
        # if [ $(zonename) = "global" ]
        #   then bootadm list-menu | awk "-F:" '/menu.lst/ {print $2}' | xargs ls -ld      
        #   else echo "This system `zonename` does not meet the requirement"
        # fi
      </procedure>
      <output>
        V-4250
        The system's boot loader configuration file(s) must have mode 0600 or less permissive.
        If menu.lst has a mode more permissive than 0600, this is a finding.
        Procedure:
        # if [ $(zonename) = "global" ]
        #   then bootadm list-menu | awk "-F:" '/menu.lst/ {print $2}' | xargs ls -ld      
        #   else echo "This system `zonename` does not meet the requirement"
        # fi
        OUTPUT:
        ->  {{ checkmyconf1.stdout }}
        ====================================================================
        This is a FINDING
        -
      </output>
      <comments>menu.lst has a mode more permissive than 0600</comments>
      <status>Ongoing</status>
      <ccis>
        <cci>CCI-</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout == "" and ansible_architecture == "i386")

- name: V-4250 Fix-1
  file: path=/rpool/boot/grub/menu.lst group=root owner=root mode=0600 state=file
  ignore_errors: True
  when: (checkmyconf2.stdout == "" and ansible_architecture == "i386" and FIX == 1)
