###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-4309 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
        v_id="V-4309"
        rule_id="SV-4309r2_rule"
        raw_risk="II"
        datetime="{{ ansible_date_time.date }}">
        <title>If the system is a firewall, ASET must be used on the system, and the firewall parameters must be set in /usr/aset/asetenv.</title>
        <discussion>ASET will not perform firewall tasks if it is not listed as a parameter in /usr/aset/asetenv.</discussion>
        <check_content>Perform the following to determine if ASET is being used.

        # crontab -l |grep aset

        A returned entry would indicate ASET is being utilized.  Determine if ASET is configured to check firewall settings.

        # grep TASKS /usr/aset/asetenv | grep firewall

        If an entry is not returned, this is a finding.</check_content>
        <fix_text>If the system is used as a firewall and ASET is used, ensure the firewall parameter is configured in /usr/aset/asetenv.</fix_text>


- name: V-4309 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: "----------------------------------------------------------------------------------------------"
    block: |
        <procedure>
          Procedure: 
          
        </procedure>
        <output>
          V-4309
            If the system is a firewall, ASET must be used on the system, and the firewall parameters must be set in /usr/aset/asetenv.
            This system is not a firewall.
            -
            This is Not Applicable
            -
        </output>
        <comments>This system is not a firewall.</comments>
        <status>Not a Finding</status>
        <ccis>
          <cci>CCI-000032</cci>
          <cci>CCI-000366</cci>
          <cci>CCI-001298</cci>
        </ccis>
      </finding>
