- name: V-807 Check
  shell: ls / | while read DIR; do find /$DIR -fstype nfs -prune -o -fstype proc -prune -type d -perm -002 ! -perm -1000 -exec ls -ld {} \;; done | awk '$3 !~ /root/'
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-807 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: "----------------------------------------------------------------------------------------------"
    block: |
      V-807
      All public directories must be owned by root or an application account.
      If any public directory is not owned by root or an application user, this is a finding.
      Procedure:
      # find / -type d -perm -1002 -exec ls -ld {} \;
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      -
      This is NOT a finding
      -
  when: (checkmyconf1.stdout == "" and REPORT == 1)

- name: V-807 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: "----------------------------------------------------------------------------------------------"
    block: |
      V-807
      All public directories must be owned by root or an application account.
      If any public directory is not owned by root or an application user, this is a finding.
      Procedure:
      # find / -type d -perm -1002 -exec ls -ld {} \;
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ====================================================================
      This is a FINDING
      -
  when: checkmyconf1.stdout != ""
