- name: V-805 Check
  shell: cat /etc/vfstab | awk '/setuid/'; zfs get setuid | awk '/on/ && !/rpool/'
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-805 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: "----------------------------------------------------------------------------------------------"
    block: |
      V-805
      Removable media, remote file systems, and any file system that does not contain approved setuid files must be mounted with the "nosuid" option.
      If any lines are returned this is a finding
      Procedure:
      # cat /etc/vfstab | awk '/setuid/'; zfs get setuid | awk '/on/'
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      -
      This is NOT a finding
      -
  when: (checkmyconf1.stdout == "" and REPORT == 1)

- name: V-805 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: "----------------------------------------------------------------------------------------------"
    block: |
      V-805
      Removable media, remote file systems, and any file system that does not contain approved setuid files must be mounted with the "nosuid" option.
      If any lines are returned this is a finding
      Procedure:
      # cat /etc/vfstab | awk '/setuid/'; zfs get setuid | awk '/on/'
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ====================================================================
      This is a FINDING
      -
  when: checkmyconf1.stdout != ""

