- name: V-814 Check
  shell: awk '/-fr/' /etc/security/audit_control
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-814 Check 2
  shell: awk '/-fr/' /etc/security/audit_control
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-814 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: "----------------------------------------------------------------------------------------------"
    block: |
      V-814
      The audit system must be configured to audit failed attempts to access files and programs.
      If flags -fr or fr are not configured, this is a finding.
      Procedure:
      # awk '/-fr/' /etc/security/audit_control
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      -
      This is NOT a finding
      -
  when: (checkmyconf2.stdout != "" and REPORT == 1)

- name: V-814 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: "----------------------------------------------------------------------------------------------"
    block: |
      V-814
      The audit system must be configured to audit failed attempts to access files and programs.
      If flags -fr or fr are not configured, this is a finding.
      Procedure:
      # awk '/-fr/' /etc/security/audit_control
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ====================================================================
      This is a FINDING
      -
  when: checkmyconf2.stdout == ""

- name: V-814 Fix-1
  lineinfile: dest=/etc/security/audit_control regexp=^flags line="flags:am,as,lo,fd,fm,-fr,ua"
  when: (checkmyconf2.stdout == "" and FIX == 1)
