- name: V-22454 Check
  shell: ls -lL /etc/syslog.conf 2>&1
  args:
    executable: /bin/bash
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22454 Check 2
  shell: ls -lL /etc/syslog.conf | awk '/\+/'
  args:
    executable: /bin/bash
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22454 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: "----------------------------------------------------------------------------------------------"
    block: |
      V-22454
      The /etc/syslog.conf file must not have an extended ACL.
      If the permissions include a "+", the file has an extended ACL and this is a finding.
      Procedure:
      # ls -lL /etc/syslog.conf
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      -
      This is NOT a finding
      -
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-22454 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: "----------------------------------------------------------------------------------------------"
    block: |
      V-22454
      The /etc/syslog.conf file must not have an extended ACL.
      If the permissions include a "+", the file has an extended ACL and this is a finding.
      Procedure:
      # ls -lL /etc/syslog.conf
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ====================================================================
      This is a FINDING
      -
  when: checkmyconf2.stdout != ""

- name: V-22454 Fix-1
  shell:  chmod A- /etc/syslog.conf
  args:
    executable: /bin/bash
  ignore_errors: True
  when: (checkmyconf2.stdout != "" and FIX == 1)
