###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-1061 Check
  shell: ls -lL /dev/audio 2>&1
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-1061 Check 2
  shell: ls -lL /dev/audio 2>/dev/null | awk '!/-rw-rw----/ {print $9}' 2>/dev/null
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-1061 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"    
    state: present
    marker: " "
    block: |
      <finding
        v_id="V-1061"
        rule_id="SV-27251r1_rule"
        raw_risk="II"
        datetime="{{ ansible_date_time.date }}">
        <title>Audio devices must be group-owned by root, sys, or bin.</title>
        <discussion>Without privileged group owners, audio devices will be vulnerable to being used as eaves-dropping devices by malicious users or intruders to possibly listen to conversations containing sensitive information.
        </discussion>
        <check_content>Check the group-owner of audio devices.

        Procedure:
        # ls -lL /dev/audio

        If the group-owner of an audio device is not root, sys, or bin, this is a finding.</check_content>
        <fix_text>Change the group owner of the audio device.

        Procedure:
        # chgrp system &lt;audio device&gt;</fix_text>
    
- name: V-1061 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: "----------------------------------------------------------------------------------------------"
    block: |
        <procedure>
          Procedure: 
          # ls -lL /dev/audio
          </procedure>
        <output>
          V-1061
        Audio devices must have mode 0660 or less permissive.
        If the mode of audio devices are more permissive than 0660, this is a finding.
        Procedure:
        # ls -lL /dev/audio
        OUTPUT:
        ->  {{ checkmyconf1.stdout }}
        -
        This is NOT a finding
        -
        </output>
        <comments>/dev/audio does not exist</comments>
        <status>Not a Finding</status>
        <ccis>
          <cci>CCI-000225</cci>
        </ccis>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-1061 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: "----------------------------------------------------------------------------------------------"
    block: |
      <procedure>
        Procedure: 
        # ls -lL /dev/audio
        </procedure>
      <output>
        V-1061
      Audio devices must have mode 0660 or less permissive.
      If the mode of audio devices are more permissive than 0660, this is a finding.
      Procedure:
      # ls -lL /dev/audio
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ====================================================================
      This is a FINDING
      -
      </output>
      <comments>/dev/audio does not exist</comments>
      <status>Ongoing</status>
      <ccis>
        <cci>CCI-000225</cci>
      </ccis>
    </finding>
      
      
  when: checkmyconf2.stdout != ""

- name: V-1061 Fix-1
  file: path="{{item}}" mode=0660 state=file
  with_items: "{{checkmyconf2.stdout_lines}}"
  ignore_errors: True
  when: (checkmyconf2.stdout != "" and FIX == 1)
