- name: V-22440 Check
  shell: awk '/\// && !/^#/' /etc/mail/aliases | awk "-F:" '{print $2}' | while read $DIR; do ls -ld $DIR; done | awk '$3 !~ /root|bin|sys/'
  args:
    executable: /bin/bash
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22440 Check 2
  shell: awk '/\// && !/^#|null/' /etc/mail/aliases | awk "-F:" '{print $2}' | while read $DIR; do ls -ld $DIR; done | awk '$3 !~ /root|bin|sys/ || $1 !~ /\+/ {print $9}'
  args:
    executable: /bin/bash
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22440 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: "----------------------------------------------------------------------------------------------"
    block: |
      V-22440 V-22441
      Files executed through a mail aliases file must be group-owned by root, bin, or sys, and must reside within a directory group-owned by root, bin, or sys.
      Files executed through a mail aliases file must not have extended ACLs.


      If the group owner of any file is not root, bin, or sys, this is a finding.
      Procedure:
      # awk '/\// && !/^#/' /etc/mail/aliases | awk "-F:" '{print $2}' | while read $DIR; do ls -ld $DIR; done | awk '$3 !~ /root|bin|sys/'
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      -
      This is NOT a finding
      -
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-22440 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: "----------------------------------------------------------------------------------------------"
    block: |
      V-22440 V-22441
      Files executed through a mail aliases file must be group-owned by root, bin, or sys, and must reside within a directory group-owned by root, bin, or sys.
      Files executed through a mail aliases file must not have extended ACLs.

      If the group owner of any file is not root, bin, or sys, this is a finding.
      Procedure:
      # awk '/\// && !/^#/' /etc/mail/aliases | awk "-F:" '{print $2}' | while read $DIR; do ls -ld $DIR; done | awk '$3 !~ /root|bin|sys/'
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ====================================================================
      This is a FINDING
      -
  when: checkmyconf2.stdout != ""

- name: V-22440 Fix-1
  file: path="{{item}}" group=root owner=root state=file
  with_items: "{{checkmyconf2.stdout_lines}}"
  ignore_errors: True
  when: (checkmyconf2.stdout != "" and FIX == 1)
